"""empty message

Revision ID: 1f845294e01a
Revises: 
Create Date: 2019-11-05 19:00:17.539850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f845294e01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btnvalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_washing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machineId', sa.Integer(), nullable=True),
    sa.Column('locationNum', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=5), nullable=True),
    sa.Column('cicle', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('start', sa.BigInteger(), nullable=True),
    sa.Column('end', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dryers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('locationNum', sa.Integer(), nullable=True),
    sa.Column('available', sa.String(length=12), nullable=True),
    sa.Column('cicle', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(length=220), nullable=True),
    sa.Column('wallet', sa.Float(precision=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_time', sa.String(length=220), nullable=True),
    sa.Column('trans_id', sa.String(length=220), nullable=True),
    sa.Column('trans_status', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_email', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_name', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_surname', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_id', sa.String(length=220), nullable=True),
    sa.Column('old_amount', sa.Float(precision=5), nullable=True),
    sa.Column('trans_amount', sa.Float(precision=5), nullable=True),
    sa.Column('new_amount', sa.Float(precision=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('washers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('postal', sa.Integer(), nullable=True),
    sa.Column('locationNum', sa.Integer(), nullable=True),
    sa.Column('available', sa.String(length=12), nullable=True),
    sa.Column('cicle_1', sa.String(length=120), nullable=True),
    sa.Column('time_1', sa.Integer(), nullable=True),
    sa.Column('price_1', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_2', sa.String(length=120), nullable=True),
    sa.Column('time_2', sa.Integer(), nullable=True),
    sa.Column('price_2', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_3', sa.String(length=120), nullable=True),
    sa.Column('time_3', sa.Integer(), nullable=True),
    sa.Column('price_3', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_4', sa.String(length=120), nullable=True),
    sa.Column('time_4', sa.Integer(), nullable=True),
    sa.Column('price_4', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_5', sa.String(length=120), nullable=True),
    sa.Column('time_5', sa.Integer(), nullable=True),
    sa.Column('price_5', sa.Float(precision=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('washers')
    op.drop_table('wallet_transactions')
    op.drop_table('users')
    op.drop_table('dryers')
    op.drop_table('current_washing')
    op.drop_table('btnvalues')
    # ### end Alembic commands ###
