"""empty message

Revision ID: 7d23eb702b50
Revises: 6abd3c19da50
Create Date: 2019-11-04 12:33:52.144258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d23eb702b50'
down_revision = '6abd3c19da50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=220), nullable=True),
    sa.Column('wallet', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
