"""empty message

Revision ID: 7e89e997ffe1
Revises: 956e02f948c2
Create Date: 2019-11-02 18:06:28.799357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e89e997ffe1'
down_revision = '956e02f948c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_washing', sa.Column('end', sa.Integer(), nullable=True))
    op.add_column('current_washing', sa.Column('start', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_washing', 'start')
    op.drop_column('current_washing', 'end')
    # ### end Alembic commands ###
