"""empty message

Revision ID: 956e02f948c2
Revises: cb27dd4df5c9
Create Date: 2019-11-02 18:06:05.681131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '956e02f948c2'
down_revision = 'cb27dd4df5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_washing', 'start_at')
    op.drop_column('current_washing', 'end_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_washing', sa.Column('end_at', mysql.TIMESTAMP(), nullable=True))
    op.add_column('current_washing', sa.Column('start_at', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
