"""empty message

Revision ID: 99f4aebada5a
Revises: a1162a6778a1
Create Date: 2019-11-02 18:04:03.105840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99f4aebada5a'
down_revision = 'a1162a6778a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_washing', 'end_at')
    op.drop_column('current_washing', 'start_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_washing', sa.Column('start_at', mysql.DATETIME(), nullable=True))
    op.add_column('current_washing', sa.Column('end_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
