"""empty message

Revision ID: a1162a6778a1
Revises: fb4a3d10f78f
Create Date: 2019-11-02 18:02:14.933814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1162a6778a1'
down_revision = 'fb4a3d10f78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_washing', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_washing', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
