"""empty message

Revision ID: b735968fdef0
Revises: 7216afdb0585
Create Date: 2019-11-04 15:17:03.614381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b735968fdef0'
down_revision = '7216afdb0585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_time', sa.Integer(), nullable=True),
    sa.Column('trans_id', sa.String(length=220), nullable=True),
    sa.Column('trans_status', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_email', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_name', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_surname', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_id', sa.String(length=220), nullable=True),
    sa.Column('old_amount', sa.Float(precision=5), nullable=True),
    sa.Column('trans_amount', sa.Float(precision=5), nullable=True),
    sa.Column('new_amount', sa.Float(precision=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
