"""empty message

Revision ID: cb27dd4df5c9
Revises: 99f4aebada5a
Create Date: 2019-11-02 18:04:19.035822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb27dd4df5c9'
down_revision = '99f4aebada5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_washing', sa.Column('end_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('current_washing', sa.Column('start_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_washing', 'start_at')
    op.drop_column('current_washing', 'end_at')
    # ### end Alembic commands ###
