"""empty message

Revision ID: cbe17ec94956
Revises: d8db7dd89fd0
Create Date: 2019-11-04 16:00:39.934986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe17ec94956'
down_revision = 'd8db7dd89fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_time', sa.String(length=220), nullable=True),
    sa.Column('trans_id', sa.String(length=220), nullable=True),
    sa.Column('trans_status', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_email', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_name', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_surname', sa.String(length=220), nullable=True),
    sa.Column('paypal_payer_id', sa.String(length=220), nullable=True),
    sa.Column('old_amount', sa.Float(precision=5), nullable=True),
    sa.Column('trans_amount', sa.Float(precision=5), nullable=True),
    sa.Column('new_amount', sa.Float(precision=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
