"""empty message

Revision ID: cd242199bdb2
Revises: 
Create Date: 2019-10-30 14:11:29.145917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd242199bdb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dryers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('cicle', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('washers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('cicle_1', sa.String(length=120), nullable=True),
    sa.Column('time_1', sa.Integer(), nullable=True),
    sa.Column('price_1', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_2', sa.String(length=120), nullable=True),
    sa.Column('time_2', sa.Integer(), nullable=True),
    sa.Column('price_2', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_3', sa.String(length=120), nullable=True),
    sa.Column('time_3', sa.Integer(), nullable=True),
    sa.Column('price_3', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_4', sa.String(length=120), nullable=True),
    sa.Column('time_4', sa.Integer(), nullable=True),
    sa.Column('price_4', sa.Float(precision=5), nullable=True),
    sa.Column('cicle_5', sa.String(length=120), nullable=True),
    sa.Column('time_5', sa.Integer(), nullable=True),
    sa.Column('price_5', sa.Float(precision=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('washers')
    op.drop_table('users')
    op.drop_table('dryers')
    # ### end Alembic commands ###
