"""empty message

Revision ID: cd73dfec2e06
Revises: 7e89e997ffe1
Create Date: 2019-11-02 18:10:22.412675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd73dfec2e06'
down_revision = '7e89e997ffe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_washing', 'start')
    op.drop_column('current_washing', 'end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_washing', sa.Column('end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('current_washing', sa.Column('start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
