"""empty message

Revision ID: fb4a3d10f78f
Revises: a197996d9cff
Create Date: 2019-11-02 16:38:27.137550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4a3d10f78f'
down_revision = 'a197996d9cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_washing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machineId', sa.Integer(), nullable=True),
    sa.Column('locationNum', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=5), nullable=True),
    sa.Column('cicle', sa.String(length=120), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_washing')
    # ### end Alembic commands ###
